-- 1. pgvector 확장 설치
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. 기존 테이블 삭제
-- DROP TABLE IF EXISTS comments CASCADE;
-- DROP TABLE IF EXISTS posts CASCADE;
-- DROP TABLE IF EXISTS categories CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- 3. categories 테이블
CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(50) NOT NULL UNIQUE,
    slug character varying(50) NOT NULL UNIQUE
);

-- 4. users 테이블
CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(100) NOT NULL UNIQUE,
    password character varying(255) NOT NULL,
    nickname character varying(50) NOT NULL UNIQUE,
    profile_image_url character varying(500),
    role character varying(20) NOT NULL CHECK (role IN ('ADMIN', 'USER'))
);

-- 5. posts 테이블
CREATE TABLE IF NOT EXISTS posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    category_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    thumbnail_url character varying(500),
    view_count integer NOT NULL DEFAULT 0,
    status character varying(20) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED')),
    content_vector vector(1536)
);

-- 6. comments 테이블
CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    post_id bigint NOT NULL,
    parent_id bigint,
    github_id character varying(50) NOT NULL,
    github_username character varying(100) NOT NULL,
    github_avatar_url character varying(500),
    content text NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false
);

-- 7. 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_post_user_id ON posts (user_id);
CREATE INDEX IF NOT EXISTS idx_post_category_id ON posts (category_id);
CREATE INDEX IF NOT EXISTS idx_post_status ON posts (status);
CREATE INDEX IF NOT EXISTS idx_post_created_at ON posts (created_at);
CREATE INDEX IF NOT EXISTS idx_comment_post_deleted_created ON comments (post_id, is_deleted, created_at);

-- 8. 확인
SELECT 'Schema created successfully!' as status;
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;
